### PR TITLE
Minor fixes to API reference autogeneration for Read the Docs

### PR DESCRIPTION
**Pull request by JSchripsema-IDM**
This treats warnings as errors in the RTD build and fixes a config issue that was causing silent warnings on the RTD build.

### CODE REVIEW

**Review by lgeorge-idm — DISMISSED** [review]
Everything works as expected. Using separate pages for the api docs is better for the modules that have a lot of methods. Defer to @DMistry-IDM & @ckerr-IDM for final approval.

**Review by cliffckerr — COMMENTED** [review]
Thanks @JSchripsema-IDM ! What do you think about porting some of the settings from the Covasim docs config, so (a) it shows the version number, (b) in the table of contents it shows up as "API reference -> Submodules" instead of  "synthpops -> synthpops package"? Screenshot below. cc @DMistry-IDM 
image

**Comment by cliffckerr** [comment]
@JSchripsema-IDM I also just noticed that both SynthPops and Covasim have any empty "Module contents" section at the bottom...not sure off the top of my head how to get rid of that

**Comment by JSchripsema-IDM** [comment]
The latest changes remove the "Module contents" and rename the modules topic with an "API reference" title. The version number, with the move to RTD, is handled by tags on the RTD backend instead of a setting in conf.py.

**Review by cliffckerr — APPROVED** [review]
Confirmed works locally!

**Pull request merged**
